### ISSUE TITLE
Import Nunito Font

### ISSUE THREAD

**Issue by tinytown-admin** [Tinytown/tinytown-react-app#21]
https://fonts.google.com/specimen/Nunito+Sans?query=nunit#standard-styles
For Nunito Sans, we use the following styles:
Black 900

https://fonts.google.com/specimen/Nunito?query=nunit
Regular 400
Bold 700
Black 900 italic

![Typography](https://user-images.githubusercontent.com/67204772/90963735-2a46b080-e46f-11ea-993d-e3b77705d7e8.png)

**Comment by alfalcon90** [comment]
Fixed with https://github.com/Tinytown/tinytown-react-app/pull/27
