### ISSUE TITLE
Floating Action Button

### ISSUE THREAD

**Issue by tinytown-admin** [Tinytown/tinytown-react-app#25]
**Blocked by #20** 

This task is for the React component. The Floating Action Button (FAB) will be used in different views as the primary button for that view. Ex: With the labels "Go to my location" and "Log in with Twitter" during Onboarding.

Redlines / Assets: https://www.figma.com/file/6HJ2ieYnB09P5eKdVl0a0c/Tinytown-MVP?node-id=42%3A4500

![Fab](https://user-images.githubusercontent.com/67204772/90964483-d5f2ff00-e475-11ea-8ba5-b9cdcb70e84a.png)

**Comment by AlexJAPPs** [comment]
Can i help?

**Comment by AlexJAPPs** [comment]
my mail: alexmasseywelson@gmail.com

**Comment by AlexJAPPs** [comment]
#32
