### ISSUE TITLE
App Navigation

### ISSUE THREAD

**Issue by tinytown-admin** [Tinytown/tinytown-react-app#44]
We need to choose a navigation library and bring it into our project. 

There's a few options out there:
https://wix.github.io/react-native-navigation/docs/before-you-start/
https://reactnavigation.org/
http://airbnb.io/native-navigation/

Seems like the general consensus is that React Navigation is the way to go given the low level of complexity of our app: https://hackernoon.com/how-to-choose-the-right-react-native-navigation-library-48679d63c9e9

Blocking #45

**Comment by abdih** [comment]
Let's go with React Navigation for now based on the argument that it's (i) simpler than RNN (includes the fact that it's JavaScript oriented) and (ii) endorsed officially by Facebook. If we run into problems, we can hopefully switch later.
